test_groups:
# https://github.com/kubernetes/test-infra/blob/master/config/testgrids/openshift/redhat-openshift-ocp-release-4.7-blocking.yaml
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-ovn-ipv6
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-ovn-ipv6
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-4.7
  name: release-openshift-ocp-installer-e2e-aws-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-serial-4.7
  name: release-openshift-ocp-installer-e2e-aws-serial-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.7
  name: release-openshift-origin-installer-e2e-aws-serial-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-4.7
  name: release-openshift-origin-installer-e2e-gcp-4.7
# https://github.com/kubernetes/test-infra/blob/master/config/testgrids/openshift/redhat-openshift-ocp-release-4.7-informing.yaml
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/canary-release-openshift-origin-installer-e2e-aws-4.7-cnv
  name: canary-release-openshift-origin-installer-e2e-aws-4.7-cnv
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-aws-proxy
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-aws-proxy
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-aws-workers-rhel7
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-aws-workers-rhel7
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted-ipv6
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted-ipv6
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted-onprem
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted-onprem
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-ovn-dualstack
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-ovn-dualstack
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-upgrade
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-upgrade
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-virtualmedia
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-ipi-virtualmedia
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-ovirt
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-ovirt
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-serial
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-serial
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-upi
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-upi
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-upi-serial
  name: periodic-ci-openshift-release-master-ocp-4.7-e2e-vsphere-upi-serial
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.7-openshift-ipi-azure-arcconformance
  name: periodic-ci-openshift-release-master-ocp-4.7-openshift-ipi-azure-arcconformance
- days_of_results: 17
  gcs_prefix: origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.7
  name: promote-release-openshift-machine-os-content-e2e-aws-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.7-ppc64le
  name: promote-release-openshift-machine-os-content-e2e-aws-4.7-ppc64le
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.7-s390x
  name: promote-release-openshift-machine-os-content-e2e-aws-4.7-s390x
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-console-aws-4.7
  name: release-openshift-ocp-installer-console-aws-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-csi-4.7
  name: release-openshift-ocp-installer-e2e-aws-csi-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-fips-4.7
  name: release-openshift-ocp-installer-e2e-aws-fips-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-fips-serial-4.7
  name: release-openshift-ocp-installer-e2e-aws-fips-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-mirrors-4.7
  name: release-openshift-ocp-installer-e2e-aws-mirrors-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-ovn-4.7
  name: release-openshift-ocp-installer-e2e-aws-ovn-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upi-4.7
  name: release-openshift-ocp-installer-e2e-aws-upi-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-4.7
  name: release-openshift-ocp-installer-e2e-azure-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-fips-4.7
  name: release-openshift-ocp-installer-e2e-azure-fips-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-fips-serial-4.7
  name: release-openshift-ocp-installer-e2e-azure-fips-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-ovn-4.7
  name: release-openshift-ocp-installer-e2e-azure-ovn-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-serial-4.7
  name: release-openshift-ocp-installer-e2e-azure-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-4.7
  name: release-openshift-ocp-installer-e2e-gcp-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-fips-4.7
  name: release-openshift-ocp-installer-e2e-gcp-fips-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-fips-serial-4.7
  name: release-openshift-ocp-installer-e2e-gcp-fips-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-ovn-4.7
  name: release-openshift-ocp-installer-e2e-gcp-ovn-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-rt-4.7
  name: release-openshift-ocp-installer-e2e-gcp-rt-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-serial-4.7
  name: release-openshift-ocp-installer-e2e-gcp-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-4.7
  name: release-openshift-ocp-installer-e2e-metal-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-compact-4.7
  name: release-openshift-ocp-installer-e2e-metal-compact-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-serial-4.7
  name: release-openshift-ocp-installer-e2e-metal-serial-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-4.7
  name: release-openshift-ocp-installer-e2e-openstack-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-serial-4.7
  name: release-openshift-ocp-installer-e2e-openstack-serial-4.7
- days_of_results: 33
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.7
  name: release-openshift-ocp-osd-aws-nightly-4.7
- days_of_results: 33
  gcs_prefix: origin-ci-test/logs/release-openshift-ocp-osd-gcp-nightly-4.7
  name: release-openshift-ocp-osd-gcp-nightly-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.7
  name: release-openshift-origin-installer-e2e-aws-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.7
  name: release-openshift-origin-installer-e2e-aws-calico-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-compact-4.7
  name: release-openshift-origin-installer-e2e-aws-compact-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-disruptive-4.7
  name: release-openshift-origin-installer-e2e-aws-disruptive-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-aws-ovn-upgrade-4.6-stable-to-4.7-ci
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-sdn-multitenant-4.7
  name: release-openshift-origin-installer-e2e-aws-sdn-multitenant-4.7
- days_of_results: 33
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.7
  name: release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-shared-vpc-4.7
  name: release-openshift-origin-installer-e2e-aws-shared-vpc-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.6-to-4.7-ci
  name: release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.6-to-4.7-ci
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-aws-upgrade-4.6-stable-to-4.7-ci
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.6-to-4.7
  name: release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.6-to-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.7
  name: release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.7
- days_of_results: 50
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-4.7
  name: release-openshift-origin-installer-e2e-azure-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-compact-4.7
  name: release-openshift-origin-installer-e2e-azure-compact-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-ovn-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-azure-ovn-upgrade-4.6-stable-to-4.7-ci
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-shared-vpc-4.7
  name: release-openshift-origin-installer-e2e-azure-shared-vpc-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-azure-upgrade-4.6-stable-to-4.7-ci
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade-4.7
  name: release-openshift-origin-installer-e2e-azure-upgrade-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-compact-4.7
  name: release-openshift-origin-installer-e2e-gcp-compact-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-ovn-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-gcp-ovn-upgrade-4.6-stable-to-4.7-ci
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-serial-4.7
  name: release-openshift-origin-installer-e2e-gcp-serial-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-shared-vpc-4.7
  name: release-openshift-origin-installer-e2e-gcp-shared-vpc-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade-4.6-stable-to-4.7-ci
  name: release-openshift-origin-installer-e2e-gcp-upgrade-4.6-stable-to-4.7-ci
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade-4.7
  name: release-openshift-origin-installer-e2e-gcp-upgrade-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-remote-libvirt-ppc64le-4.7
  name: release-openshift-origin-installer-e2e-remote-libvirt-ppc64le-4.7
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-remote-libvirt-s390x-4.7
  name: release-openshift-origin-installer-e2e-remote-libvirt-s390x-4.7
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-old-rhcos-e2e-aws-4.7
  name: release-openshift-origin-installer-old-rhcos-e2e-aws-4.7
# https://github.com/kubernetes/test-infra/blob/master/config/testgrids/openshift/redhat-openshift-ocp-release-4.8-blocking.yaml
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-ovn-ipv6
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-ovn-ipv6
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-4.8
  name: release-openshift-ocp-installer-e2e-aws-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-serial-4.8
  name: release-openshift-ocp-installer-e2e-aws-serial-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.8
  name: release-openshift-origin-installer-e2e-aws-serial-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-4.8
  name: release-openshift-origin-installer-e2e-gcp-4.8
# https://github.com/kubernetes/test-infra/blob/master/config/testgrids/openshift/redhat-openshift-ocp-release-4.8-informing.yaml
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-aws-proxy
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-aws-proxy
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted-ipv6
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted-ipv6
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted-onprem
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-assisted-onprem
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-ovn-dualstack
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-ovn-dualstack
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-upgrade
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-upgrade
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-virtualmedia
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-metal-ipi-virtualmedia
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-ovirt
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-ovirt
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-serial
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-serial
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-upi
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-upi
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-upi-serial
  name: periodic-ci-openshift-release-master-ocp-4.8-e2e-vsphere-upi-serial
- gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.8-openshift-ipi-azure-arcconformance
  name: periodic-ci-openshift-release-master-ocp-4.8-openshift-ipi-azure-arcconformance
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-console-aws-4.8
  name: release-openshift-ocp-installer-console-aws-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-fips-4.8
  name: release-openshift-ocp-installer-e2e-aws-fips-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-ovn-4.8
  name: release-openshift-ocp-installer-e2e-aws-ovn-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upi-4.8
  name: release-openshift-ocp-installer-e2e-aws-upi-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-4.8
  name: release-openshift-ocp-installer-e2e-azure-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-ovn-4.8
  name: release-openshift-ocp-installer-e2e-azure-ovn-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-serial-4.8
  name: release-openshift-ocp-installer-e2e-azure-serial-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-4.8
  name: release-openshift-ocp-installer-e2e-gcp-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-ovn-4.8
  name: release-openshift-ocp-installer-e2e-gcp-ovn-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-rt-4.8
  name: release-openshift-ocp-installer-e2e-gcp-rt-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-serial-4.8
  name: release-openshift-ocp-installer-e2e-gcp-serial-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-4.8
  name: release-openshift-ocp-installer-e2e-metal-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-serial-4.8
  name: release-openshift-ocp-installer-e2e-metal-serial-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.8
  name: release-openshift-ocp-osd-aws-nightly-4.8
- gcs_prefix: origin-ci-test/logs/release-openshift-ocp-osd-gcp-nightly-4.8
  name: release-openshift-ocp-osd-gcp-nightly-4.8
- days_of_results: 60
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.8
  name: release-openshift-origin-installer-e2e-aws-calico-4.8
- days_of_results: 33
  gcs_prefix: origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.8
  name: release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.8
